import { testSeriesSchema, testSetSchemaVersion } from "./schema.js";

/**
 * The frozen F-00 test set.
 *
 * `docs/research/consistency-gate.md` §2 fixes this before the first generation
 * and forbids swapping it afterwards: the four gates are ratios over these thirty
 * shots, so changing the set retroactively changes every gate. Treat edits here
 * the same way as edits to the gate definitions — only for the re-freeze triggers
 * in §8, and only before a run.
 *
 * Why one continuous two-and-a-half minute fragment rather than thirty unrelated
 * shots: Gate C asks whether failures cluster and Gate D asks whether the
 * sequence is publishable *as a stretch of an episode*. Neither question can be
 * asked of a shot grab-bag.
 *
 * Reference images are not in the repository. They are produced once, by hand,
 * before the first run and kept in the run directory — see
 * `docs/research/provider-evaluation.md`. `path` is relative to
 * `PLOTPOP_RESEARCH_ASSET_DIR`.
 */
export const midnightNoodleRun = testSeriesSchema.parse({
  schemaVersion: testSetSchemaVersion,
  id: "midnight-noodle-run",
  title: "Midnight Noodle Run",
  frozenOn: "2026-07-29",

  styleGuide: {
    id: "pop-anime-neon",
    name: "Pop Anime Neon",
    lineWork: "Bold uniform ink outlines, no sketch lines, corners kept crisp",
    coloring: "Flat cel shading with two-step shadows, no gradients on skin",
    rendering: "Hard-edged rim light from signage, visible rain streaks, no bloom haze",
    palette: ["#12102A", "#F2E9DE", "#FF3E7F", "#3EE0D0", "#FFC53E"],
    avoid: [
      "Photoreal skin texture or realistic pores",
      "Soft airbrushed gradients and lens flare",
      "Western comic cross-hatching",
      "On-screen text, subtitles or signage lettering in any language",
    ],
  },

  characters: [
    {
      id: "rio-alvarez",
      versionId: "rio-alvarez-v1",
      name: "Rio Alvarez",
      appearance: {
        face: "Round jaw, wide-set eyes, a small scar through the left eyebrow",
        hair: "Black undercut, longer on top, one teal streak above the right temple",
        eyes: "Dark brown, thick lower lashes",
        build: "Nineteen, short and wiry, stands with weight on the back foot",
      },
      wardrobe:
        "Orange bomber jacket with a reflective stripe down each sleeve, black cargo shorts, high-top sneakers, courier headset over the right ear",
      references: [
        { view: "front", path: "characters/rio-alvarez/front.png" },
        { view: "three_quarter", path: "characters/rio-alvarez/three-quarter.png" },
        { view: "back", path: "characters/rio-alvarez/back.png" },
        { view: "expression_neutral", path: "characters/rio-alvarez/neutral.png" },
        { view: "expression_emotive", path: "characters/rio-alvarez/grin.png" },
      ],
      voice: { locale: "en-US", timbre: "Bright, fast, slightly breathless" },
    },
    {
      id: "mika-reed",
      versionId: "mika-reed-v1",
      name: "Mika Tanaka-Reed",
      appearance: {
        face: "Long oval face, high cheekbones, round wire glasses",
        hair: "Dark brown, shoulder length, tied back with a folded red bandana",
        eyes: "Hazel, heavy upper lids",
        build: "Twenty-two, tall, square shoulders, forearms of someone who lifts pots",
      },
      wardrobe:
        "Indigo work shirt with sleeves rolled to the elbow, cream apron stained at the hip, black trousers, rubber clogs",
      references: [
        { view: "front", path: "characters/mika-reed/front.png" },
        { view: "three_quarter", path: "characters/mika-reed/three-quarter.png" },
        { view: "back", path: "characters/mika-reed/back.png" },
        { view: "expression_neutral", path: "characters/mika-reed/neutral.png" },
        { view: "expression_emotive", path: "characters/mika-reed/exasperated.png" },
      ],
      voice: { locale: "en-US", timbre: "Low, dry, unhurried" },
    },
    {
      id: "hale-song",
      versionId: "hale-song-v1",
      name: "Hale Song",
      appearance: {
        face: "Narrow face, sharp nose, deep line between the brows",
        hair: "Grey-streaked black, swept back, close-cropped at the sides",
        eyes: "Grey, hooded, rarely fully open",
        build: "Late thirties, lean and tall, hands usually in pockets",
      },
      wardrobe:
        "Ankle-length charcoal coat over a grey turtleneck, thin leather gloves, boots with a steel toe cap",
      references: [
        { view: "front", path: "characters/hale-song/front.png" },
        { view: "three_quarter", path: "characters/hale-song/three-quarter.png" },
        { view: "back", path: "characters/hale-song/back.png" },
        { view: "expression_neutral", path: "characters/hale-song/neutral.png" },
        { view: "expression_emotive", path: "characters/hale-song/narrowed.png" },
      ],
      voice: { locale: "en-US", timbre: "Quiet, clipped, lands on consonants" },
    },
  ],

  scenes: [
    {
      id: "market-alley",
      name: "Night market alley",
      location: "A three-metre-wide alley between food stalls, wet asphalt, no sky visible",
      timeOfDay: "night",
      lighting: "Magenta and cyan signage from both walls, one dead bulb halfway down",
      setDressing: [
        "Stacked plastic crates against the left wall",
        "Steam venting from a grate at ankle height",
        "Hanging cloth banners, unlettered",
        "A parked delivery scooter with a top box",
      ],
    },
    {
      id: "noodle-counter",
      name: "Noodle counter interior",
      location: "A seven-seat counter, cook on the far side, roll-up shutter half closed behind",
      timeOfDay: "night",
      lighting: "Warm tungsten pendants over the counter, cold spill from the street behind",
      setDressing: [
        "Two stock pots on a gas ring, one lid rattling",
        "A wall clock with a bent minute hand",
        "Stacked lacquer bowls and a bundle of chopsticks",
        "Insulated delivery crates by the door",
      ],
    },
    {
      id: "rooftop-overlook",
      name: "Rooftop overlook",
      location: "A flat tar roof above the market, low parapet on the far edge",
      timeOfDay: "night",
      lighting: "Cold blue ambient, market glow rising from below, one red antenna beacon",
      setDressing: [
        "A forest of antenna masts and guy wires",
        "A humming air-handling unit",
        "A propped fire door with a brick",
        "Puddles holding the beacon's reflection",
      ],
    },
  ],

  shots: [
    // --- Scene 1: market alley ------------------------------------------------
    {
      id: "shot-01",
      sceneId: "market-alley",
      rank: 100,
      framing: "wide",
      beat: "establishing",
      cameraMotion: "static",
      characterIds: [],
      durationSeconds: 6,
      action: "Rain falls through the signage glow; steam drifts across the empty alley.",
    },
    {
      id: "shot-02",
      sceneId: "market-alley",
      rank: 200,
      framing: "wide",
      beat: "establishing",
      cameraMotion: "pan",
      characterIds: ["rio-alvarez"],
      durationSeconds: 5,
      action: "Rio's scooter swings into the alley mouth and slows, headlight sweeping the wall.",
    },
    {
      id: "shot-03",
      sceneId: "market-alley",
      rank: 300,
      framing: "medium",
      beat: "action",
      cameraMotion: "handheld",
      characterIds: ["rio-alvarez"],
      durationSeconds: 4,
      action:
        "Rio brakes hard and plants one sneaker in a puddle, jacket stripe catching the light.",
    },
    {
      id: "shot-04",
      sceneId: "market-alley",
      rank: 400,
      framing: "close_up",
      beat: "reaction",
      cameraMotion: "static",
      characterIds: ["rio-alvarez"],
      durationSeconds: 3,
      action: "Rio squints at a cracked phone screen; rain beads on the glass.",
    },
    {
      id: "shot-05",
      sceneId: "market-alley",
      rank: 500,
      framing: "medium",
      beat: "action",
      cameraMotion: "push_in",
      characterIds: ["rio-alvarez"],
      durationSeconds: 5,
      action:
        "Rio hauls an insulated bag off the scooter's top box and slings it across one shoulder.",
    },
    {
      id: "shot-06",
      sceneId: "market-alley",
      rank: 600,
      framing: "wide",
      beat: "action",
      cameraMotion: "crane",
      characterIds: ["rio-alvarez"],
      durationSeconds: 6,
      action: "Rio runs down the alley past the crates, banners lifting in the draught behind.",
    },
    {
      id: "shot-07",
      sceneId: "market-alley",
      rank: 700,
      framing: "close_up",
      beat: "dialogue",
      cameraMotion: "static",
      characterIds: ["rio-alvarez"],
      durationSeconds: 4,
      action: "Rio speaks into the headset mid-stride, breath visible.",
      dialogue: [{ characterId: "rio-alvarez", line: "Two minutes out. Keep the lid on." }],
    },
    {
      id: "shot-08",
      sceneId: "market-alley",
      rank: 800,
      framing: "medium",
      beat: "dialogue",
      cameraMotion: "pan",
      characterIds: ["rio-alvarez", "hale-song"],
      durationSeconds: 5,
      action: "Hale steps out of a doorway into Rio's path; Rio stops short, half a metre away.",
      dialogue: [
        { characterId: "hale-song", line: "Wrong alley." },
        { characterId: "rio-alvarez", line: "Right alley. Wrong night to stand in it." },
      ],
    },
    {
      id: "shot-09",
      sceneId: "market-alley",
      rank: 900,
      framing: "close_up",
      beat: "reaction",
      cameraMotion: "static",
      characterIds: ["hale-song"],
      durationSeconds: 3,
      action: "Hale's eyes narrow; the line between the brows deepens.",
    },
    {
      id: "shot-10",
      sceneId: "market-alley",
      rank: 1000,
      framing: "wide",
      beat: "action",
      cameraMotion: "pull_out",
      characterIds: ["rio-alvarez", "hale-song"],
      durationSeconds: 6,
      action:
        "Rio ducks under Hale's arm and keeps running; Hale turns to watch, hands in pockets.",
    },

    // --- Scene 2: noodle counter ---------------------------------------------
    {
      id: "shot-11",
      sceneId: "noodle-counter",
      rank: 1100,
      framing: "wide",
      beat: "establishing",
      cameraMotion: "static",
      characterIds: [],
      durationSeconds: 5,
      action: "Seven empty stools under warm pendants; steam curls past the half-closed shutter.",
    },
    {
      id: "shot-12",
      sceneId: "noodle-counter",
      rank: 1200,
      framing: "medium",
      beat: "action",
      cameraMotion: "static",
      characterIds: ["mika-reed"],
      durationSeconds: 4,
      action: "Mika slams a rattling lid back onto the pot and wipes both hands on the apron.",
    },
    {
      id: "shot-13",
      sceneId: "noodle-counter",
      rank: 1300,
      framing: "close_up",
      beat: "action",
      cameraMotion: "push_in",
      characterIds: ["mika-reed"],
      durationSeconds: 3,
      action: "A nest of noodles drops into boiling water; Mika's gloved fingers pull clear.",
    },
    {
      id: "shot-14",
      sceneId: "noodle-counter",
      rank: 1400,
      framing: "medium",
      beat: "dialogue",
      cameraMotion: "static",
      characterIds: ["mika-reed", "rio-alvarez"],
      durationSeconds: 6,
      action: "Rio arrives at the counter dripping; Mika does not look up from the pot.",
      dialogue: [
        { characterId: "mika-reed", line: "You're wet." },
        { characterId: "rio-alvarez", line: "It's raining. That's how that works." },
      ],
    },
    {
      id: "shot-15",
      sceneId: "noodle-counter",
      rank: 1500,
      framing: "close_up",
      beat: "dialogue",
      cameraMotion: "static",
      characterIds: ["rio-alvarez"],
      durationSeconds: 4,
      action: "Rio leans on the counter, chin down, and holds up four fingers.",
      dialogue: [{ characterId: "rio-alvarez", line: "You said eight bowls." }],
    },
    {
      id: "shot-16",
      sceneId: "noodle-counter",
      rank: 1600,
      framing: "close_up",
      beat: "dialogue",
      cameraMotion: "static",
      characterIds: ["mika-reed"],
      durationSeconds: 4,
      action: "Mika tips the glasses down and looks over the rim.",
      dialogue: [{ characterId: "mika-reed", line: "I said eight. At eight." }],
    },
    {
      id: "shot-17",
      sceneId: "noodle-counter",
      rank: 1700,
      framing: "medium",
      beat: "reaction",
      cameraMotion: "handheld",
      characterIds: ["rio-alvarez", "mika-reed"],
      durationSeconds: 5,
      action: "Both heads turn to the wall clock with its bent minute hand.",
    },
    {
      id: "shot-18",
      sceneId: "noodle-counter",
      rank: 1800,
      framing: "wide",
      beat: "action",
      cameraMotion: "pan",
      characterIds: ["rio-alvarez", "mika-reed"],
      durationSeconds: 6,
      action:
        "The two of them load lidded bowls into an insulated crate, passing them hand to hand.",
    },
    {
      id: "shot-19",
      sceneId: "noodle-counter",
      rank: 1900,
      framing: "close_up",
      beat: "action",
      cameraMotion: "static",
      characterIds: ["mika-reed"],
      durationSeconds: 3,
      action: "Mika pulls the crate strap tight and knots it twice.",
    },
    {
      id: "shot-20",
      sceneId: "noodle-counter",
      rank: 2000,
      framing: "medium",
      beat: "dialogue",
      cameraMotion: "push_in",
      characterIds: ["mika-reed"],
      durationSeconds: 4,
      action: "Mika pushes the crate across the counter and holds it there a beat.",
      dialogue: [{ characterId: "mika-reed", line: "Rooftop. Don't tip it." }],
    },
    {
      id: "shot-21",
      sceneId: "noodle-counter",
      rank: 2100,
      framing: "wide",
      beat: "action",
      cameraMotion: "pull_out",
      characterIds: ["rio-alvarez"],
      durationSeconds: 5,
      action: "Rio backs out through the shutter with the crate braced against one hip.",
    },

    // --- Scene 3: rooftop overlook -------------------------------------------
    {
      id: "shot-22",
      sceneId: "rooftop-overlook",
      rank: 2200,
      framing: "wide",
      beat: "establishing",
      cameraMotion: "crane",
      characterIds: [],
      durationSeconds: 6,
      action: "Antenna masts and guy wires stand against cold blue; the red beacon pulses once.",
    },
    {
      id: "shot-23",
      sceneId: "rooftop-overlook",
      rank: 2300,
      framing: "medium",
      beat: "action",
      cameraMotion: "handheld",
      characterIds: ["rio-alvarez"],
      durationSeconds: 5,
      action: "Rio shoulders the fire door open, crate first, and kicks the brick back into place.",
    },
    {
      id: "shot-24",
      sceneId: "rooftop-overlook",
      rank: 2400,
      framing: "wide",
      beat: "action",
      cameraMotion: "pan",
      characterIds: ["rio-alvarez"],
      durationSeconds: 6,
      action: "Rio crosses the roof between puddles, ducking under a low guy wire.",
    },
    {
      id: "shot-25",
      sceneId: "rooftop-overlook",
      rank: 2500,
      framing: "medium",
      beat: "dialogue",
      cameraMotion: "static",
      characterIds: ["rio-alvarez", "hale-song"],
      durationSeconds: 5,
      action: "Hale is already at the parapet. Rio sets the crate down between them.",
      dialogue: [
        { characterId: "rio-alvarez", line: "You took the stairs." },
        { characterId: "hale-song", line: "I took the lift." },
      ],
    },
    {
      id: "shot-26",
      sceneId: "rooftop-overlook",
      rank: 2600,
      framing: "close_up",
      beat: "dialogue",
      cameraMotion: "static",
      characterIds: ["hale-song"],
      durationSeconds: 4,
      action: "Hale checks a wrist without a watch on it, then looks up.",
      dialogue: [{ characterId: "hale-song", line: "Four minutes late." }],
    },
    {
      id: "shot-27",
      sceneId: "rooftop-overlook",
      rank: 2700,
      framing: "close_up",
      beat: "reaction",
      cameraMotion: "static",
      characterIds: ["rio-alvarez"],
      durationSeconds: 3,
      action: "Rio breathes hard, teal streak plastered flat, and says nothing.",
    },
    {
      id: "shot-28",
      sceneId: "rooftop-overlook",
      rank: 2800,
      framing: "medium",
      beat: "action",
      cameraMotion: "static",
      characterIds: ["rio-alvarez", "hale-song", "mika-reed"],
      durationSeconds: 6,
      action: "Mika arrives through the fire door with two spare bowls and hands one to Hale.",
    },
    {
      id: "shot-29",
      sceneId: "rooftop-overlook",
      rank: 2900,
      framing: "close_up",
      beat: "reaction",
      cameraMotion: "push_in",
      characterIds: ["mika-reed"],
      durationSeconds: 3,
      action: "Mika grins, glasses fogging in the steam off the bowl.",
    },
    {
      id: "shot-30",
      sceneId: "rooftop-overlook",
      rank: 3000,
      framing: "wide",
      beat: "reaction",
      cameraMotion: "pull_out",
      characterIds: ["rio-alvarez", "mika-reed", "hale-song"],
      durationSeconds: 7,
      action: "The three of them eat on the parapet, backs to camera, market glow rising below.",
    },
  ],
});
